# Generated by Django 3.0.3 on 2020-03-21 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_md_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('feed_md_name', models.CharField(max_length=100)),
                ('feed_content', models.TextField()),
                ('feed_upload_dttm', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_feed',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('feed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Feed')),
            ],
            options={
                'db_table': 'tb_feed_like',
                'unique_together': {('feed_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('upload_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('feed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Feed')),
            ],
            options={
                'db_table': 'tb_feed_comment',
                'unique_together': {('feed_id', 'user_id')},
            },
        ),
    ]
